name: Update README

on:
  schedule:
    - cron: "40 4 * * 6"
  push:
    paths:
      - ".github/workflows/update-readme.yml"
  workflow_dispatch:

jobs:
  update-github-activity:
    name: Update README with GitHub Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          GH_USERNAME: ${{ github.actor }}
          COMMIT_NAME: "GitHub Activity Readme"
          COMMIT_MSG: "Update README with the recent activity"
          MAX_LINES: 10
          TARGET_FILE: README.md
          EMPTY_COMMIT_MSG: "No recent activity to update the README"

  update-wakatime-stats:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          COMMIT_MESSAGE: "Update README with WakaTime stats"
          COMMIT_USERNAME: "github-actions[bot]"

  update-streak-stats:
    name: Update Streak Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&disable_animations=true
          path: images/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push